index:
   path: /
   controller: App\Controller\DefaultController::index

redirectHomepage:
   path: /homepage
   controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
   defaults: 
      route: 'blog/{name}'
      title: 'test title'
      permanent: false
      keepQueryParams: false
